site_name: Arrowhead 5 | java-spring
repo_name: eclipse-arrowhead
repo_url: https://github.com/eclipse-arrowhead
nav:
  - Home:
    - Welcome: home/welcome.md
    - Implementation: home/implementation.md
    - Getting Started: home/getting_started.md
    - Contribute: home/contribute.md 
  - Core Systems:
    - Service Registry: core_systems/service_registry.md
    - Service Orchestration: core_systems/service_orchestration.md
    - Authorization: core_systems/authorization.md
    - Authentication: core_systems/authentication.md
  - Support Systems: support_systems.md
  - API:
    - Interface Descriptions:
      - General:
        - HTTP:
          - general-management: api/general/general-management-generic-http.md
      - Service Registry:
        - HTTP:
          - device-discovery: api/serviceregistry/device-discovery-generic-http.md
          - system-discovery: api/serviceregistry/system-discovery-generic-http.md
        - MQTT:
          - device-discovery: api/serviceregistry/device-discovery-generic-mqtt.md
          - system-discovery: api/serviceregistry/system-discovery-generic-mqtt.md     
      - Authentication:
        - HTTP:
          - identity: api/authentication/identity-generic-http.md
          - identity-management: api/authentication/identity-management-generic-http.md
    - Authentication Policy: api/authentication_policy.md
    - Data Models:
      - AddressDescriptor: api/data-models/address-descriptor.md
      - ConfigMap: api/data-models/config-map.md
      - ConfigResponse: api/data-models/config-response.md
      - Credentials: api/data-models/credentials.md
      - DeviceDescriptor: api/data-models/device-descriptor.md
      - DeviceLookupRequest: api/data-models/device-lookup-request.md
      - DeviceLookupResponse: api/data-models/device-lookup-response.md
      - DeviceLookupResult: api/data-models/device-lookup-result.md
      - DeviceRegistrationRequest: api/data-models/device-registration-request.md
      - DeviceRegistrationResponse: api/data-models/device-registration-response.md
      - ErrorResponse: api/data-models/error-response.md
      - Identity: api/data-models/identity.md
      - IdentityChangeRequest: api/data-models/identity-change-request.md
      - IdentityListCreateRequest: api/data-models/identity-list-create-request.md
      - IdentityListResponse: api/data-models/identity-list-response.md
      - IdentityMgmtRequest: api/data-odels/identity-mgmt-request.md
      - IdentityQueryRequest: api/data-models/identity-query-request.md
      - IdentityRequest: api/data-models/identity-request.md
      - IdentityResponse: api/data-models/identity-response.md
      - IdentityResult: api/data-models/identity-result.md
      - IdentityListUpdateRequest: api/data-models/identity-list-update-request.md
      - IdentityVerifyResponse: api/data-models/identity-verify-response.md
      - LogEntry: api/data-models/log-entry.md
      - LogRequest: api/data-models/log-request.md
      - LogResponse: api/data-models/log-response.md
      - Metadata: api/data-models/metadata.md
      - MetadataRequirements: api/data-models/metadata-requirements.md
      - MQTTRequestTemplate: api/data-models/mqtt-request-template.md
      - MQTTResponseTemplate: api/data-models/mqtt-response-template.md
      - PageRequest: api/data-models/page-request.md
      - SystemLookupRequest: api/data-models/system-lookup-request.md
      - SystemLookupResponse: api/data-models/system-lookup-response.md
      - SystemLookupResult: api/data-models/system-lookup-result.md
      - SystemRegistrationRequest: api/data-models/system-registration-request.md
      - SystemRegistrationResponse: api/data-models/system-registration-response.md
    - Primitives: api/primitives.md
  - Help:
    - Certificate Profiles: help/certificate-profiles.md
    - Tutorials:
      - Service Registry Demo: help/tutorials/serviceregistry-http-demo.md
      - Mosquitto MQTT Broker: help/tutorials/mosquitto-mqtt-broker.md
      - Create Certificates: help/tutorials/create-certificates.md
    - Hints: help/hints.md
    - FAQ: help/faq.md
  - Client Libraries: client_libraries.md
theme:
  name: material
  logo: assets/logo.png
  favicon: assets/favicon.png
  icon:
      repo: fontawesome/brands/github 
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.tracking
    - toc.follow
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - icons
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: blue
      accent: green 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: blue
      accent: green

extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/eclipse-arrowhead

markdown_extensions:
  - attr_list
  - toc:
      toc_depth: 4
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
